version: "3.9"

services:
  postgres:
    image: postgres:16
    container_name: rampay-postgres
    environment:
      POSTGRES_USER: rampay
      POSTGRES_PASSWORD: rampay
      POSTGRES_DB: rampaydb
    ports:
      - "5432:5432"
    volumes:
      - pgdata:/var/lib/postgresql/data

  redis:
    image: redis:7
    container_name: rampay-redis
    ports:
      - "6379:6379"
    command: ["redis-server", "--appendonly", "yes"]

volumes:
  pgdata:
